name: Continuous delivery

on:
  push:
    branches:
      - main
jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: "Init repository"
        uses: actions/checkout@v3

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: "Install dependencies"
        run: composer install

      - name: "Audit dependencies"
        run: composer audit

      - name: "Run PHPStan"
        run: composer phpstan
      - name: Login to github docker registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: sunnybenji
            password: ${{ secrets.TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/sunnybenji/docker_rendu:1.0.0