name: Continuous delivery

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: "Init repository"
        uses: actions/checkout@v3

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: "Install dependencies"
        run: composer install

      - name: "Audit dependencies"
        run: composer audit

      - name: "Run PHPStan"
        run: composer phpstan

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: sunnybenji
          password: ${{ secrets.TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/sunnybenji/swap:latest
      - name: SSH into DigitalOcean server and pull Docker image
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop swap || true
            docker rm swap || true
            docker login ghcr.io -u sunnybenji -p ${{ secrets.TOKEN }}
            docker pull ghcr.io/sunybenji/swap:latest
            docker run -d --name swap -p 9000:9000 -v /volume:/var/www/html/ ghcr.io/sunnybenji/swap:latest
            
